# Generated by Django 5.1.2 on 2024-11-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Skill',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('Html', 'Html')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Part_Time', 'Part_Time'), ('Full_Time', 'Full_Time')], max_length=50, null=True)),
                ('Skill', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('Html', 'Html')], max_length=50, null=True)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('vecancy', models.IntegerField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Media/Job_pic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.TextField(null=True)),
                ('resume', models.FileField(null=True, upload_to='Media/Resume')),
                ('Apply_pic', models.ImageField(null=True, upload_to='Media/Resume')),
                ('Skill', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.jobmodel')),
            ],
        ),
    ]
